name: Testing Mask
on:
  push:

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Mask GCP token
        env:
          ACTIONS_STEP_DEBUG: false
        run: |
          export token="123" > /dev/null 2>&1
